name: app_environment
channels:
  - snowflake
dependencies:
  - catboost=*
  - imbalanced-learn=*
  - ipython=*
  - joblib=*
  - loky=*
  - matplotlib=*
  - numpy=*
  - pandas=*
  - psutil=*
  - scikit-learn=*
  - seaborn=*
  - xgboost=*
